version: '3'
services:
  server:
    build: ./server
    image: server
    ports:
      - "3000:3000"
    depends_on:
      - hello-world-service
      - product-descp-service
      - product-price-service
  hello-world-service:
    build: ./hello-world-service
    image: hello-world
  product-descp-service:
    build: ./product-descp-service
    image: product-descp
  product-price-service:
    build: ./product-price-service
    image: product-price

